name: Release Toolbox

on:
  push:
    branches:
      - main

jobs:
  release-toolbox:
   runs-on: ubuntu-latest
   permissions: write-all
   steps:
     - name: Check out repository
       uses: actions/checkout@v3
       with:
           fetch-depth: '0'
     - name: Set up MATLAB
       uses: matlab-actions/setup-matlab@v1
     - name: Run script
       uses: matlab-actions/run-command@v1
       with:
         command: cd buildUtilities, releaseTask("1.0"), cd ..
     - name: Generate Git Tag
       id: generate_tag
       run: |
        VERSION_PREFIX="v"
        VERSION_MAJOR_MINOR="1.0"
        VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
        if [ -z "$VERSION_PATCH" ]; then
          VERSION_PATCH=0
        else
          VERSION_PATCH=$((VERSION_PATCH + 1))
        fi
        NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
     - name: Push Git Tag
       run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag $NEW_TAG
        git push origin $NEW_TAG
