
name: Deploy Application

on:
  push:
   branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: '0'

    - name: Generate Git Tag
      id: generate_tag
      run: |
        NEW_TAG=`git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}'`
        echo "Generated new tag: $NEW_TAG"

    - name: Push Git Tag
      run: |
        git config user.name "rcgob"
        git config user.email "rodrigocgob@gmail.com"
        git tag $NEW_TAG
        git push origin $NEW_TAG

    # Add your build, test, and deploy steps here
